# Variables
CXX = 
CXXFLAGS = 
OBJECTS = 
PROGRAMS = 

# a good question to ask is what are CXX and CXXFLAGS?

# Targets and Dependencies - implement each of these below

#all:

#tee: 

#tee.o: 

#clean:
